### PR TITLE
Fix https://github.com/tonyfettes/coc-rime/issues/6

### PR DESCRIPTION
**Pull request by Freed-Wu**

### CODE REVIEW

**Comment by Freed-Wu** [comment]
@tonyfettes Can you add me to collaborator of this project and <https://github.com/tonyfettes/coc-rime>? TIA!

**Comment by tonyfettes** [comment]
Sure, just sent an invitation.

**Comment by Freed-Wu** [comment]
> Sure, just sent an invitation.

And this project?

**Comment by tonyfettes** [comment]
@Freed-Wu sorry my mistake 🙇‍♂️

**Comment by Freed-Wu** [comment]
Thanks!

**Comment by Freed-Wu** [comment]
Can you invite me to maintainers of <https://www.npmjs.com/package/coc-rime> for `npm publish`? TIA!

**Comment by tonyfettes** [comment]
image

Is this you?

**Comment by Freed-Wu** [comment]
Yes! :+1:

**Pull request merged**
